name = "SPRFitting"
uuid = "d8a8d3c8-1875-4c31-a7a0-fa97855a07fa"
authors = ["Sam Isaacson <isaacsas@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DataStructures = "0.18.11"
UnPack = "1.0.2"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
