name = "SPRFitting"
uuid = "d8a8d3c8-1875-4c31-a7a0-fa97855a07fa"
authors = ["Sam Isaacson <isaacsas@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
